apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: mlops-pf
type: Opaque
data:
  postgres-user: bWxvcHNfdXNlcg==
  postgres-password: bWxvcHNfcGFzc3dvcmQ=
  postgres-db: bWxvcHNfcmVhbF9lc3RhdGU=

---
apiVersion: v1
kind: Secret
metadata:
  name: airflow-secret
  namespace: mlops-pf
type: Opaque
data:
  airflow-db-user: YWlyZmxvd191c2Vy
  airflow-db-password: YWlyZmxvd19wYXNzd29yZA==
  airflow-db: YWlyZmxvd19kYg==
  airflow-admin-user: YWlyZmxvdw==
  airflow-admin-password: YWlyZmxvdw==
  airflow-secret-key: bWxvcHNfcmVhbF9lc3RhdGVfYWlyZmxvd19zZWNyZXRfa2V5XzIwMjY=

---
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: mlops-pf
type: Opaque
data:
  minio-root-user: bWluaW9hZG1pbg==
  minio-root-password: bWluaW9hZG1pbg==
  aws-access-key-id: bWluaW9hZG1pbg==
  aws-secret-access-key: bWluaW9hZG1pbg==