apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: mlops-pf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      initContainers:
        - name: wait-for-mlflow
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              until wget -q --spider http://mlflow:5000/health; do
                echo "Esperando MLflow...";
                sleep 5;
              done
        - name: wait-for-postgres
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              until nc -z postgres 5432; do
                echo "Esperando PostgreSQL...";
                sleep 5;
              done
      containers:
        - name: api
          image: jchapadockerhub/mlops-pf-api:latest
          ports:
            - containerPort: 8000
          env:
            - name: MLFLOW_TRACKING_URI
              valueFrom:
                configMapKeyRef:
                  name: mlflow-config
                  key: MLFLOW_TRACKING_URI
            - name: MLFLOW_MODEL_NAME
              valueFrom:
                configMapKeyRef:
                  name: mlflow-config
                  key: MLFLOW_MODEL_NAME
            - name: MLFLOW_MODEL_ALIAS
              valueFrom:
                configMapKeyRef:
                  name: mlflow-config
                  key: MLFLOW_MODEL_ALIAS
            - name: MLFLOW_S3_ENDPOINT_URL
              valueFrom:
                configMapKeyRef:
                  name: mlflow-config
                  key: MLFLOW_S3_ENDPOINT_URL
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: aws-access-key-id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: aws-secret-access-key
            - name: POSTGRES_HOST
              value: postgres
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-db
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-password
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 40
            periodSeconds: 15
            failureThreshold: 3