apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: mlops-pf
spec:
  selector:
    app: api
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: api-external
  namespace: mlops-pf
spec:
  selector:
    app: api
  ports:
    - port: 8000
      targetPort: 8000
  type: LoadBalancer