apiVersion: v1
kind: Service
metadata:
  name: airflow-webserver
  namespace: mlops-pf
spec:
  selector:
    app: airflow-webserver
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: airflow-external
  namespace: mlops-pf
spec:
  selector:
    app: airflow-webserver
  ports:
    - port: 8081
      targetPort: 8080
  type: LoadBalancer