apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit
  namespace: mlops-pf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit
  template:
    metadata:
      labels:
        app: streamlit
    spec:
      initContainers:
        - name: wait-for-api
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              until wget -q --spider http://api:8000/health; do
                echo "Esperando API...";
                sleep 5;
              done
      containers:
        - name: streamlit
          image: jchapadockerhub/mlops-pf-streamlit:latest
          ports:
            - containerPort: 8501
          env:
            - name: API_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: streamlit-config
                  key: API_BASE_URL
            - name: POSTGRES_HOST
              value: postgres
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-db
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-password
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /_stcore/health
              port: 8501
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /_stcore/health
              port: 8501
            initialDelaySeconds: 40
            periodSeconds: 15
            failureThreshold: 3